// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemasAnaliticos.Models;

#nullable disable

namespace SistemasAnaliticos.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260223222710_cambio de char a string")]
    partial class cambiodecharastring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.AlcanceUsuario", b =>
                {
                    b.Property<int>("idAlcance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAlcance"));

                    b.Property<string>("alcance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idAlcance");

                    b.HasIndex("rolId")
                        .IsUnique();

                    b.ToTable("AlcanceUsuario");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Auditoria", b =>
                {
                    b.Property<int>("idAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAudit"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("idAudit");

                    b.HasIndex("Fecha");

                    b.HasIndex("Tabla");

                    b.HasIndex("Usuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Beneficio", b =>
                {
                    b.Property<long>("idBeneficio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idBeneficio"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("idBeneficio");

                    b.ToTable("Beneficio");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Constancia", b =>
                {
                    b.Property<long>("idConstancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idConstancia"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("datosAdjuntos")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dirijido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("fechaRequerida")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("tamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("tipoMIME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idConstancia");

                    b.ToTable("Constancia");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Extras", b =>
                {
                    b.Property<long>("idExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idExtra"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("jefe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoExtra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalHoras")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idExtra");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.ExtrasDetalle", b =>
                {
                    b.Property<long>("idExtrasDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idExtrasDetalle"));

                    b.Property<string>("atm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("horaFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("horaInicio")
                        .HasColumnType("time");

                    b.Property<long>("idExtra")
                        .HasColumnType("bigint");

                    b.Property<string>("lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noBoleta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noCaso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idExtrasDetalle");

                    b.HasIndex("idExtra");

                    b.ToTable("ExtrasDetalle");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Fotos", b =>
                {
                    b.Property<long>("idFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idFoto"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("foto")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("idFoto");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Garantia", b =>
                {
                    b.Property<long>("idGarantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idGarantia"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aFavorDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("datosAdjuntos1")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("datosAdjuntos2")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("datosAdjuntos3")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("datosAdjuntos4")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("datosAdjuntos5")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaFinalizacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaInicio")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("monto")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nombreArchivo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreArchivo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreArchivo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreArchivo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreArchivo5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreLicitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroLicitacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("prorroga")
                        .HasColumnType("bit");

                    b.Property<long?>("tamanoArchivo1")
                        .HasColumnType("bigint");

                    b.Property<long?>("tamanoArchivo2")
                        .HasColumnType("bigint");

                    b.Property<long?>("tamanoArchivo3")
                        .HasColumnType("bigint");

                    b.Property<long?>("tamanoArchivo4")
                        .HasColumnType("bigint");

                    b.Property<long?>("tamanoArchivo5")
                        .HasColumnType("bigint");

                    b.Property<string>("tipoLicitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGarantia");

                    b.ToTable("Garantia");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.LiquidacionViatico", b =>
                {
                    b.Property<long>("idViatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idViatico"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("jefe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idViatico");

                    b.ToTable("LiquidacionViatico");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.LiquidacionViaticoDetalle", b =>
                {
                    b.Property<long>("idViaticoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idViaticoDetalle"));

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<long>("idViatico")
                        .HasColumnType("bigint");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idViaticoDetalle");

                    b.HasIndex("idViatico");

                    b.ToTable("LiquidacionViaticoDetalle");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Noticias", b =>
                {
                    b.Property<long>("idNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idNoticia"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contenidoTexto")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("fechaPublicacion")
                        .HasColumnType("date");

                    b.Property<byte[]>("foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<TimeSpan>("horaPublicacion")
                        .HasColumnType("time");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNoticia");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Permiso", b =>
                {
                    b.Property<long>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idPermiso"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("datosAdjuntos")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("fechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaRegresoLaboral")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<TimeSpan?>("horaCita")
                        .HasColumnType("time");

                    b.Property<string>("motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("tamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMIME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPermiso");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RolId", "Clave")
                        .IsUnique();

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("cantidadHijos")
                        .HasColumnType("int");

                    b.Property<string>("canton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("celularOficina")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("celularPersonal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("contactoEmergencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("correoEmpresa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("correoPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuentaIBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("diasVacaciones")
                        .HasColumnType("int");

                    b.Property<string>("direccionExacta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("distrito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("estadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("extension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("fechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("genero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("hijos")
                        .HasColumnType("bit");

                    b.Property<string>("jefeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("jefeNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("lastActivityUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("licencias")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("noEmpleado")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("padecimientosAlergias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("primerApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("primerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("profesion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("puesto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("salario")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("segundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("segundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefonoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("telefonoHabitacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipoPariente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipoSangre")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("ultimaFechaCalculoVacaciones")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("cedula")
                        .IsUnique()
                        .HasFilter("[cedula] IS NOT NULL");

                    b.HasIndex("correoEmpresa")
                        .IsUnique()
                        .HasFilter("[correoEmpresa] IS NOT NULL");

                    b.HasIndex("departamento");

                    b.HasIndex("estado");

                    b.HasIndex("fechaIngreso");

                    b.HasIndex("jefeId");

                    b.HasIndex("noEmpleado");

                    b.HasIndex("primerNombre");

                    b.HasIndex("puesto");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.UsuarioSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioSesion", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.ExtrasDetalle", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Extras", "Extra")
                        .WithMany("Detalles")
                        .HasForeignKey("idExtra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.LiquidacionViaticoDetalle", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.LiquidacionViatico", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("idViatico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", "Jefe")
                        .WithMany("Subordinados")
                        .HasForeignKey("jefeId");

                    b.Navigation("Jefe");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.UsuarioSesion", b =>
                {
                    b.HasOne("SistemasAnaliticos.Entidades.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Extras", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.LiquidacionViatico", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemasAnaliticos.Entidades.Usuario", b =>
                {
                    b.Navigation("Subordinados");
                });
#pragma warning restore 612, 618
        }
    }
}
